# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

module FirecrackerApis

using Random
using Dates
using HTTP
using Swagger
import Swagger: set_field!, get_field, isset_field, validate_field, SwaggerApi, SwaggerModel
import Base: convert

include("modelincludes.jl")

include("api_DefaultApi.jl")

# export models
export convert, BootSource
export convert, CpuTemplate
export convert, Drive
export convert, Error
export convert, InstanceActionInfo
export convert, InstanceInfo
export convert, Logger
export convert, MachineConfiguration
export convert, NetworkInterface
export convert, PartialDrive
export convert, RateLimiter
export convert, TokenBucket

# export operations
export convert, DefaultApi

export check_required, set_field!, get_field, isset_field, convert

end
