# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

mutable struct PartialDrive <: SwaggerModel
    drive_id::Union{ Nothing, String } # drive_id
    path_on_host::Union{ Nothing, String } # path_on_host

    function PartialDrive(;drive_id=nothing, path_on_host=nothing)
        o = new()
        set_field!(o, :drive_id, drive_id)
        set_field!(o, :path_on_host, path_on_host)
        o
    end
end # type PartialDrive

const _name_map_PartialDrive = Dict{String,Symbol}(["drive_id"=>:drive_id, "path_on_host"=>:path_on_host])
const _field_map_PartialDrive = Dict{Symbol,String}([:drive_id=>"drive_id", :path_on_host=>"path_on_host"])
Swagger.name_map(::Type{ PartialDrive }) = _name_map_PartialDrive
Swagger.field_map(::Type{ PartialDrive }) = _field_map_PartialDrive

function check_required(o::PartialDrive)
    (o.drive_id === nothing) && (return false)
    (o.path_on_host === nothing) && (return false)
    true
end

function validate_field(o::PartialDrive, name::Symbol, val)
end
