# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

mutable struct InstanceActionInfo <: SwaggerModel
    action_type::Union{ Nothing, String } # action_type
    payload::Union{ Nothing, String } # payload

    function InstanceActionInfo(;action_type=nothing, payload=nothing)
        o = new()
        set_field!(o, :action_type, action_type)
        set_field!(o, :payload, payload)
        o
    end
end # type InstanceActionInfo

const _name_map_InstanceActionInfo = Dict{String,Symbol}(["action_type"=>:action_type, "payload"=>:payload])
const _field_map_InstanceActionInfo = Dict{Symbol,String}([:action_type=>"action_type", :payload=>"payload"])
Swagger.name_map(::Type{ InstanceActionInfo }) = _name_map_InstanceActionInfo
Swagger.field_map(::Type{ InstanceActionInfo }) = _field_map_InstanceActionInfo

const _allowed_InstanceActionInfo_action_type = ["BlockDeviceRescan", "FlushMetrics", "InstanceStart", "SendCtrlAltDel"]

function check_required(o::InstanceActionInfo)
    true
end

function validate_field(o::InstanceActionInfo, name::Symbol, val)
    if name === :action_type
        Swagger.validate_param(name, "InstanceActionInfo", :enum, val, _allowed_InstanceActionInfo_action_type)
    end
end
