# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

mutable struct CpuTemplate <: SwaggerModel

    function CpuTemplate(;)
        o = new()
        o
    end
end # type CpuTemplate

const _name_map_CpuTemplate = Dict{String,Symbol}([])
const _field_map_CpuTemplate = Dict{Symbol,String}([])
Swagger.name_map(::Type{ CpuTemplate }) = _name_map_CpuTemplate
Swagger.field_map(::Type{ CpuTemplate }) = _field_map_CpuTemplate

function check_required(o::CpuTemplate)
    true
end

function validate_field(o::CpuTemplate, name::Symbol, val)
end
