# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

mutable struct Error <: SwaggerModel
    fault_message::Union{ Nothing, String } # fault_message

    function Error(;fault_message=nothing)
        o = new()
        set_field!(o, :fault_message, fault_message)
        o
    end
end # type Error

const _name_map_Error = Dict{String,Symbol}(["fault_message"=>:fault_message])
const _field_map_Error = Dict{Symbol,String}([:fault_message=>"fault_message"])
Swagger.name_map(::Type{ Error }) = _name_map_Error
Swagger.field_map(::Type{ Error }) = _field_map_Error

function check_required(o::Error)
    true
end

function validate_field(o::Error, name::Symbol, val)
end
