# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

mutable struct BootSource <: SwaggerModel
    kernel_image_path::Union{ Nothing, String } # kernel_image_path
    boot_args::Union{ Nothing, String } # boot_args

    function BootSource(;kernel_image_path=nothing, boot_args=nothing)
        o = new()
        set_field!(o, :kernel_image_path, kernel_image_path)
        set_field!(o, :boot_args, boot_args)
        o
    end
end # type BootSource

const _name_map_BootSource = Dict{String,Symbol}(["kernel_image_path"=>:kernel_image_path, "boot_args"=>:boot_args])
const _field_map_BootSource = Dict{Symbol,String}([:kernel_image_path=>"kernel_image_path", :boot_args=>"boot_args"])
Swagger.name_map(::Type{ BootSource }) = _name_map_BootSource
Swagger.field_map(::Type{ BootSource }) = _field_map_BootSource

function check_required(o::BootSource)
    (o.kernel_image_path === nothing) && (return false)
    true
end

function validate_field(o::BootSource, name::Symbol, val)
end
