# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

mutable struct MachineConfiguration <: SwaggerModel
    vcpu_count::Union{ Nothing, Int32 } # vcpu_count
    mem_size_mib::Union{ Nothing, Int32 } # mem_size_mib
    ht_enabled::Union{ Nothing, Bool } # ht_enabled
    cpu_template::Union{ Nothing, CpuTemplate } # cpu_template

    function MachineConfiguration(;vcpu_count=nothing, mem_size_mib=nothing, ht_enabled=nothing, cpu_template=nothing)
        o = new()
        set_field!(o, :vcpu_count, vcpu_count)
        set_field!(o, :mem_size_mib, mem_size_mib)
        set_field!(o, :ht_enabled, ht_enabled)
        set_field!(o, :cpu_template, cpu_template)
        o
    end
end # type MachineConfiguration

const _name_map_MachineConfiguration = Dict{String,Symbol}(["vcpu_count"=>:vcpu_count, "mem_size_mib"=>:mem_size_mib, "ht_enabled"=>:ht_enabled, "cpu_template"=>:cpu_template])
const _field_map_MachineConfiguration = Dict{Symbol,String}([:vcpu_count=>"vcpu_count", :mem_size_mib=>"mem_size_mib", :ht_enabled=>"ht_enabled", :cpu_template=>"cpu_template"])
Swagger.name_map(::Type{ MachineConfiguration }) = _name_map_MachineConfiguration
Swagger.field_map(::Type{ MachineConfiguration }) = _field_map_MachineConfiguration

function check_required(o::MachineConfiguration)
    true
end

function validate_field(o::MachineConfiguration, name::Symbol, val)
    if name === :vcpu_count
        Swagger.validate_param(name, "MachineConfiguration", :maximum, val, 32, false)
        Swagger.validate_param(name, "MachineConfiguration", :minimum, val, 1, false)
    end
end
