# This file was generated by the Julia Swagger Code Generator
# Do not modify this file directly. Modify the swagger specification instead.

mutable struct RateLimiter <: SwaggerModel
    bandwidth::Union{ Nothing, TokenBucket } # bandwidth
    ops::Union{ Nothing, TokenBucket } # ops

    function RateLimiter(;bandwidth=nothing, ops=nothing)
        o = new()
        set_field!(o, :bandwidth, bandwidth)
        set_field!(o, :ops, ops)
        o
    end
end # type RateLimiter

const _name_map_RateLimiter = Dict{String,Symbol}(["bandwidth"=>:bandwidth, "ops"=>:ops])
const _field_map_RateLimiter = Dict{Symbol,String}([:bandwidth=>"bandwidth", :ops=>"ops"])
Swagger.name_map(::Type{ RateLimiter }) = _name_map_RateLimiter
Swagger.field_map(::Type{ RateLimiter }) = _field_map_RateLimiter

function check_required(o::RateLimiter)
    true
end

function validate_field(o::RateLimiter, name::Symbol, val)
end
